version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: devops-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
      - app_app-network

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: devops-alertmanager
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - "9093:9093"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: devops-grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
      - app_app-network

networks:
  monitoring-net:
    driver: bridge
  app_app-network:
    external: true
