apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: ghcr.io/your-username/devops-backend
    newTag: sha-10cea0d
  - name: ghcr.io/your-username/devops-frontend
    newTag: sha-10cea0d
