apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: ghcr.io/baongdqu/devops-webserver/backend
    newTag: sha-10cea0d
  - name: ghcr.io/baongdqu/devops-webserver/frontend
    newTag: sha-10cea0d
